# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        AddWindow.setObjectName("AddWindow")
        AddWindow.resize(600, 275)
        self.centralwidget = QtWidgets.QWidget(AddWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(25, 40, 225, 25))
        self.name.setObjectName("name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(25, 10, 150, 20))
        self.label.setObjectName("label")
        self.roast_degree = QtWidgets.QComboBox(self.centralwidget)
        self.roast_degree.setGeometry(QtCore.QRect(25, 100, 225, 25))
        self.roast_degree.setObjectName("roast_degree")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(25, 70, 150, 20))
        self.label_2.setObjectName("label_2")
        self.type = QtWidgets.QComboBox(self.centralwidget)
        self.type.setGeometry(QtCore.QRect(25, 160, 225, 25))
        self.type.setObjectName("type")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(25, 130, 150, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(325, 10, 150, 20))
        self.label_4.setObjectName("label_4")
        self.flavor = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.flavor.setGeometry(QtCore.QRect(325, 40, 225, 25))
        self.flavor.setObjectName("flavor")
        self.price = QtWidgets.QSpinBox(self.centralwidget)
        self.price.setGeometry(QtCore.QRect(325, 100, 225, 25))
        self.price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.price.setMaximum(1000000)
        self.price.setSingleStep(10)
        self.price.setObjectName("price")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(325, 70, 150, 20))
        self.label_5.setObjectName("label_5")
        self.volume = QtWidgets.QSpinBox(self.centralwidget)
        self.volume.setGeometry(QtCore.QRect(325, 160, 225, 25))
        self.volume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.volume.setMaximum(1000000)
        self.volume.setSingleStep(10)
        self.volume.setObjectName("volume")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(325, 130, 150, 20))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 210, 100, 25))
        self.pushButton.setObjectName("pushButton")
        AddWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AddWindow)
        self.statusbar.setObjectName("statusbar")
        AddWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddWindow)
        QtCore.QMetaObject.connectSlotsByName(AddWindow)

    def retranslateUi(self, AddWindow):
        _translate = QtCore.QCoreApplication.translate
        AddWindow.setWindowTitle(_translate("AddWindow", "MainWindow"))
        self.label.setText(_translate("AddWindow", "Название сорта"))
        self.label_2.setText(_translate("AddWindow", "Степень обжарки"))
        self.label_3.setText(_translate("AddWindow", "Молотый/В зернах"))
        self.label_4.setText(_translate("AddWindow", "Описание вкуса"))
        self.label_5.setText(_translate("AddWindow", "Цена, руб."))
        self.label_6.setText(_translate("AddWindow", "Объем упаковки, см3"))
        self.pushButton.setText(_translate("AddWindow", "PushButton"))
